# Generated by Django 4.1.5 on 2023-01-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_text', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
